ci: add sample stack test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -275,6 +275,143 @@ jobs:
           go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
           ginkgo $STACK_DIR/test
 
+  # TODO: reuse workflows, https://docs.github.com/cn/actions/using-workflows/reusing-workflows
+  test-stack-sample:
+    runs-on: ubuntu-latest
+    needs:
+      - create-vm
+      - install-kind
+    env:
+      stack_dir: sample
+    steps:
+      - name: Check out
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Configure SSH
+        env:
+          SSH_KEY: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}
+          SSH_USER: ubuntu
+          SSH_HOST: ${{ needs.create-vm.outputs.public_ip }}
+        run: |
+          mkdir -p ~/.ssh/
+          echo "$SSH_KEY" > ~/.ssh/kind.key
+          chmod 600 ~/.ssh/kind.key
+          cat >>~/.ssh/config <<END
+          Host kind
+            HostName $SSH_HOST
+            User $SSH_USER
+            IdentityFile ~/.ssh/kind.key
+            StrictHostKeyChecking no
+          END
+
+      - name: Create Kind Cluster
+        id: create-kind-cluster
+        env:
+          KIND_NAME: ${{ env.stack_dir }}
+        run: |
+          n=0
+          until [ $n -ge 5 ] ; do
+            ingress_http_port=$(shuf -i 2000-65000 -n 1)
+            ingress_https_port=$(shuf -i 2000-65000 -n 1)
+            kube_apiserver_port=$(shuf -i 2000-65000 -n 1)
+            buildkit_port=$(shuf -i 2000-65000 -n 1)
+            echo "::set-output name=ingress_http_port::$ingress_http_port"
+            echo "::set-output name=ingress_https_port::$ingress_https_port"
+            echo "::set-output name=kube_apiserver_port::$kube_apiserver_port"
+            echo "::set-output name=buildkit_port::$buildkit_port"
+            export KIND_NAME=$KIND_NAME
+            if ssh kind 'bash -s' < ./scripts/create-kind.sh $KIND_NAME $ingress_http_port $ingress_https_port $kube_apiserver_port $buildkit_port; then
+              break
+            fi
+            echo "Waiting for kind to be available..."
+            n=$((n+1))
+            sleep 20
+          done
+          if [ $n -ge 5 ]; then
+              echo "Failed to install kind"
+              exit 1
+          fi
+
+      - name: Get Kind Kubeconfig
+        env:
+          API_SERVER_PORT: ${{ steps.create-kind-cluster.outputs.kube_apiserver_port }}
+          API_SERVER_HOST: ${{ needs.create-vm.outputs.public_ip }}
+          KIND_NAME: ${{ env.stack_dir }}
+        run: |
+          mkdir -p ~/.kube
+          export KIND_NAME=$KIND_NAME
+          scp kind:~/.kube/config-$KIND_NAME ~/.kube/config
+          sed -i 's#server: https.*$#server: https://kubernetes:'$API_SERVER_PORT'#g' ~/.kube/config
+          echo "$API_SERVER_HOST kubernetes" | sudo tee -a /etc/hosts
+
+      - name: Install Kubectl
+        uses: azure/setup-kubectl@v2.0
+        with:
+          version: v1.23.4
+
+      - name: Wait for Kind
+        id: wait_for_kube_apiserver
+        run: |
+          n=0
+          until [ $n -ge 20 ] ; do
+            if kubectl get nodes; then
+              break
+            fi
+            n=$((n+1))
+            sleep 10
+          done
+          if [ $n -ge 20 ]; then
+              echo "Timeout waiting for Kind to be running"
+              exit 1
+          fi
+
+      - name: Install hln
+        run: |
+          base_url=https://dl.h8r.io/hln/releases
+          export HLN_VERSION=$(curl -s ${base_url}/latest_version)
+          export HLN_TARBALL="heighliner_v${HLN_VERSION}_linux_amd64.tar.gz"
+          echo "Installing hln, version $HLN_VERSION"
+          curl -L ${base_url}/${HLN_VERSION}/${HLN_TARBALL} | sudo tar zxf - -C /usr/local/bin
+          hln version
+
+      - name: Hln Init
+        run: |
+          hln init
+
+      - name: Stacks Cue Vendor
+        run: |
+          make vendor
+
+      - name: hln up
+        id: hln_up
+        env:
+          STACK_DIR: ${{ env.stack_dir }}
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+          ORGANIZATION: heigliner-robot
+          HLN_LOG_LEVEL: "debug"
+          HLN_LOG_FORMAT: "plain"
+        run: |
+          export APP_NAME="$STACK_DIR-$(date +'%Y-%m-%dt%H-%M-%S' -d '+8 hour')"
+          echo "::set-output name=app_name::$APP_NAME"
+          hln up --dir $STACK_DIR
+
+      - name: Setup Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.18
+
+      - name: Run Ginkgo Tests
+        env:
+          APP_NAME: ${{ steps.hln_up.outputs.app_name }}
+          GITHUB_TOKEN: ${{ secrets.TOKEN }}
+          ORGANIZATION: heigliner-robot
+          STACK_DIR: ${{ env.stack_dir }}
+        run: |
+          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
+          ginkgo $STACK_DIR/test
+
   delete-vm:
     runs-on: ubuntu-latest
     # all stack test job should be added to needs
@@ -282,6 +419,7 @@ jobs:
       - create-vm
       - install-kind
       - test-stack
+      - test-stack-sample
     if: ${{ always() }}
     steps:
       - name: Install Tencent Cloud CLI
